project:
  type: website

website:
  title: ""
  navbar:
    background: primary
    search: true
    left:
      - text: "DigComp "
        file: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    page-layout: full
